apiVersion: v1
kind: ConfigMap
metadata:
  name: product-catalog-config
  namespace: default
  labels:
    app.kubernetes.io/name: product-catalog
    app.kubernetes.io/part-of: enterprise-devsecops-pipeline
data:
  LOG_LEVEL: "info"
  PORT: "5000"
  ENV: "production"
