apiVersion: v1
kind: Secret
metadata:
  name: product-catalog-secret
  namespace: default
  labels:
    app.kubernetes.io/name: product-catalog
    app.kubernetes.io/part-of: enterprise-devsecops-pipeline
type: Opaque
data:
  # Base64 encoded value of "my-super-secret-api-key-12345"
  API_KEY: bXktc3VwZXItc2VjcmV0LWFwaS1rZXktMTIzNDU=
