apiVersion: v1
kind: Secret
metadata:
  name: {{ include "product-catalog.fullname" . }}-secret
  labels:
    {{- include "product-catalog.labels" . | nindent 4 }}
type: Opaque
data:
  API_KEY: {{ .Values.secret.apiKey | quote }}
